/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CalculadorasIndexRouteImport } from './routes/calculadoras.index'
import { Route as CalculadorasCalculadoraAhorroMetaRouteImport } from './routes/calculadoras.calculadora-ahorro-meta'
import { Route as CalculadorasCalculadoraCapacidadEndeudamientoRouteImport } from './routes/calculadoras.calculadora-capacidad-endeudamiento'
import { Route as CalculadorasCalculadoraFiniquitoMexicoRouteImport } from './routes/calculadoras.calculadora-finiquito-mexico'
import { Route as CalculadorasCalculadoraHipotecaRouteImport } from './routes/calculadoras.calculadora-hipoteca'
import { Route as CalculadorasCalculadoraInteresCompuestoRouteImport } from './routes/calculadoras.calculadora-interes-compuesto'
import { Route as CalculadorasCalculadoraJubilacionRouteImport } from './routes/calculadoras.calculadora-jubilacion'
import { Route as CalculadorasCalculadoraPagoAnticipadoRouteImport } from './routes/calculadoras.calculadora-pago-anticipado'
import { Route as CalculadorasCalculadoraPagoDeudasRouteImport } from './routes/calculadoras.calculadora-pago-deudas'
import { Route as CalculadorasCalculadoraPrestacionesRdRouteImport } from './routes/calculadoras.calculadora-prestaciones-rd'
import { Route as CalculadorasCalculadoraPrestamoEmpresarialRouteImport } from './routes/calculadoras.calculadora-prestamo-empresarial'
import { Route as CalculadorasCalculadoraPrestamoEstudiantilRouteImport } from './routes/calculadoras.calculadora-prestamo-estudiantil'
import { Route as CalculadorasCalculadoraPrestamoPersonalRouteImport } from './routes/calculadoras.calculadora-prestamo-personal'
import { Route as CalculadorasCalculadoraPrestamoVehicularRouteImport } from './routes/calculadoras.calculadora-prestamo-vehicular'
import { Route as CalculadorasCalculadoraPresupuestoMensualRouteImport } from './routes/calculadoras.calculadora-presupuesto-mensual'
import { Route as CalculadorasCalculadoraRefinanciamientoRouteImport } from './routes/calculadoras.calculadora-refinanciamiento'
import { Route as CalculadorasCalculadoraSalarioNetoRouteImport } from './routes/calculadoras.calculadora-salario-neto'
import { Route as CalculadorasCalculadoraTarjetaCreditoRouteImport } from './routes/calculadoras.calculadora-tarjeta-credito'
import { Route as CalculadorasComparadorDePrestamosRouteImport } from './routes/calculadoras.comparador-de-prestamos'
import { Route as CalculadorasConversorDeMonedaRouteImport } from './routes/calculadoras.conversor-de-moneda'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasIndexRoute = CalculadorasIndexRouteImport.update({
  id: '/calculadoras/',
  path: '/calculadoras/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasCalculadoraAhorroMetaRoute =
  CalculadorasCalculadoraAhorroMetaRouteImport.update({
    id: '/calculadoras/calculadora-ahorro-meta',
    path: '/calculadoras/calculadora-ahorro-meta',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraCapacidadEndeudamientoRoute =
  CalculadorasCalculadoraCapacidadEndeudamientoRouteImport.update({
    id: '/calculadoras/calculadora-capacidad-endeudamiento',
    path: '/calculadoras/calculadora-capacidad-endeudamiento',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraFiniquitoMexicoRoute =
  CalculadorasCalculadoraFiniquitoMexicoRouteImport.update({
    id: '/calculadoras/calculadora-finiquito-mexico',
    path: '/calculadoras/calculadora-finiquito-mexico',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraHipotecaRoute =
  CalculadorasCalculadoraHipotecaRouteImport.update({
    id: '/calculadoras/calculadora-hipoteca',
    path: '/calculadoras/calculadora-hipoteca',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraInteresCompuestoRoute =
  CalculadorasCalculadoraInteresCompuestoRouteImport.update({
    id: '/calculadoras/calculadora-interes-compuesto',
    path: '/calculadoras/calculadora-interes-compuesto',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraJubilacionRoute =
  CalculadorasCalculadoraJubilacionRouteImport.update({
    id: '/calculadoras/calculadora-jubilacion',
    path: '/calculadoras/calculadora-jubilacion',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraPagoAnticipadoRoute =
  CalculadorasCalculadoraPagoAnticipadoRouteImport.update({
    id: '/calculadoras/calculadora-pago-anticipado',
    path: '/calculadoras/calculadora-pago-anticipado',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraPagoDeudasRoute =
  CalculadorasCalculadoraPagoDeudasRouteImport.update({
    id: '/calculadoras/calculadora-pago-deudas',
    path: '/calculadoras/calculadora-pago-deudas',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraPrestacionesRdRoute =
  CalculadorasCalculadoraPrestacionesRdRouteImport.update({
    id: '/calculadoras/calculadora-prestaciones-rd',
    path: '/calculadoras/calculadora-prestaciones-rd',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraPrestamoEmpresarialRoute =
  CalculadorasCalculadoraPrestamoEmpresarialRouteImport.update({
    id: '/calculadoras/calculadora-prestamo-empresarial',
    path: '/calculadoras/calculadora-prestamo-empresarial',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraPrestamoEstudiantilRoute =
  CalculadorasCalculadoraPrestamoEstudiantilRouteImport.update({
    id: '/calculadoras/calculadora-prestamo-estudiantil',
    path: '/calculadoras/calculadora-prestamo-estudiantil',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraPrestamoPersonalRoute =
  CalculadorasCalculadoraPrestamoPersonalRouteImport.update({
    id: '/calculadoras/calculadora-prestamo-personal',
    path: '/calculadoras/calculadora-prestamo-personal',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraPrestamoVehicularRoute =
  CalculadorasCalculadoraPrestamoVehicularRouteImport.update({
    id: '/calculadoras/calculadora-prestamo-vehicular',
    path: '/calculadoras/calculadora-prestamo-vehicular',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraPresupuestoMensualRoute =
  CalculadorasCalculadoraPresupuestoMensualRouteImport.update({
    id: '/calculadoras/calculadora-presupuesto-mensual',
    path: '/calculadoras/calculadora-presupuesto-mensual',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraRefinanciamientoRoute =
  CalculadorasCalculadoraRefinanciamientoRouteImport.update({
    id: '/calculadoras/calculadora-refinanciamiento',
    path: '/calculadoras/calculadora-refinanciamiento',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraSalarioNetoRoute =
  CalculadorasCalculadoraSalarioNetoRouteImport.update({
    id: '/calculadoras/calculadora-salario-neto',
    path: '/calculadoras/calculadora-salario-neto',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasCalculadoraTarjetaCreditoRoute =
  CalculadorasCalculadoraTarjetaCreditoRouteImport.update({
    id: '/calculadoras/calculadora-tarjeta-credito',
    path: '/calculadoras/calculadora-tarjeta-credito',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasComparadorDePrestamosRoute =
  CalculadorasComparadorDePrestamosRouteImport.update({
    id: '/calculadoras/comparador-de-prestamos',
    path: '/calculadoras/comparador-de-prestamos',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasConversorDeMonedaRoute =
  CalculadorasConversorDeMonedaRouteImport.update({
    id: '/calculadoras/conversor-de-moneda',
    path: '/calculadoras/conversor-de-moneda',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/privacidad': typeof PrivacidadRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/terminos': typeof TerminosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calculadoras/calculadora-ahorro-meta': typeof CalculadorasCalculadoraAhorroMetaRoute
  '/calculadoras/calculadora-capacidad-endeudamiento': typeof CalculadorasCalculadoraCapacidadEndeudamientoRoute
  '/calculadoras/calculadora-finiquito-mexico': typeof CalculadorasCalculadoraFiniquitoMexicoRoute
  '/calculadoras/calculadora-hipoteca': typeof CalculadorasCalculadoraHipotecaRoute
  '/calculadoras/calculadora-interes-compuesto': typeof CalculadorasCalculadoraInteresCompuestoRoute
  '/calculadoras/calculadora-jubilacion': typeof CalculadorasCalculadoraJubilacionRoute
  '/calculadoras/calculadora-pago-anticipado': typeof CalculadorasCalculadoraPagoAnticipadoRoute
  '/calculadoras/calculadora-pago-deudas': typeof CalculadorasCalculadoraPagoDeudasRoute
  '/calculadoras/calculadora-prestaciones-rd': typeof CalculadorasCalculadoraPrestacionesRdRoute
  '/calculadoras/calculadora-prestamo-empresarial': typeof CalculadorasCalculadoraPrestamoEmpresarialRoute
  '/calculadoras/calculadora-prestamo-estudiantil': typeof CalculadorasCalculadoraPrestamoEstudiantilRoute
  '/calculadoras/calculadora-prestamo-personal': typeof CalculadorasCalculadoraPrestamoPersonalRoute
  '/calculadoras/calculadora-prestamo-vehicular': typeof CalculadorasCalculadoraPrestamoVehicularRoute
  '/calculadoras/calculadora-presupuesto-mensual': typeof CalculadorasCalculadoraPresupuestoMensualRoute
  '/calculadoras/calculadora-refinanciamiento': typeof CalculadorasCalculadoraRefinanciamientoRoute
  '/calculadoras/calculadora-salario-neto': typeof CalculadorasCalculadoraSalarioNetoRoute
  '/calculadoras/calculadora-tarjeta-credito': typeof CalculadorasCalculadoraTarjetaCreditoRoute
  '/calculadoras/comparador-de-prestamos': typeof CalculadorasComparadorDePrestamosRoute
  '/calculadoras/conversor-de-moneda': typeof CalculadorasConversorDeMonedaRoute
  '/blog/': typeof BlogIndexRoute
  '/calculadoras/': typeof CalculadorasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/privacidad': typeof PrivacidadRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/terminos': typeof TerminosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calculadoras/calculadora-ahorro-meta': typeof CalculadorasCalculadoraAhorroMetaRoute
  '/calculadoras/calculadora-capacidad-endeudamiento': typeof CalculadorasCalculadoraCapacidadEndeudamientoRoute
  '/calculadoras/calculadora-finiquito-mexico': typeof CalculadorasCalculadoraFiniquitoMexicoRoute
  '/calculadoras/calculadora-hipoteca': typeof CalculadorasCalculadoraHipotecaRoute
  '/calculadoras/calculadora-interes-compuesto': typeof CalculadorasCalculadoraInteresCompuestoRoute
  '/calculadoras/calculadora-jubilacion': typeof CalculadorasCalculadoraJubilacionRoute
  '/calculadoras/calculadora-pago-anticipado': typeof CalculadorasCalculadoraPagoAnticipadoRoute
  '/calculadoras/calculadora-pago-deudas': typeof CalculadorasCalculadoraPagoDeudasRoute
  '/calculadoras/calculadora-prestaciones-rd': typeof CalculadorasCalculadoraPrestacionesRdRoute
  '/calculadoras/calculadora-prestamo-empresarial': typeof CalculadorasCalculadoraPrestamoEmpresarialRoute
  '/calculadoras/calculadora-prestamo-estudiantil': typeof CalculadorasCalculadoraPrestamoEstudiantilRoute
  '/calculadoras/calculadora-prestamo-personal': typeof CalculadorasCalculadoraPrestamoPersonalRoute
  '/calculadoras/calculadora-prestamo-vehicular': typeof CalculadorasCalculadoraPrestamoVehicularRoute
  '/calculadoras/calculadora-presupuesto-mensual': typeof CalculadorasCalculadoraPresupuestoMensualRoute
  '/calculadoras/calculadora-refinanciamiento': typeof CalculadorasCalculadoraRefinanciamientoRoute
  '/calculadoras/calculadora-salario-neto': typeof CalculadorasCalculadoraSalarioNetoRoute
  '/calculadoras/calculadora-tarjeta-credito': typeof CalculadorasCalculadoraTarjetaCreditoRoute
  '/calculadoras/comparador-de-prestamos': typeof CalculadorasComparadorDePrestamosRoute
  '/calculadoras/conversor-de-moneda': typeof CalculadorasConversorDeMonedaRoute
  '/blog': typeof BlogIndexRoute
  '/calculadoras': typeof CalculadorasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/privacidad': typeof PrivacidadRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/terminos': typeof TerminosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/calculadoras/calculadora-ahorro-meta': typeof CalculadorasCalculadoraAhorroMetaRoute
  '/calculadoras/calculadora-capacidad-endeudamiento': typeof CalculadorasCalculadoraCapacidadEndeudamientoRoute
  '/calculadoras/calculadora-finiquito-mexico': typeof CalculadorasCalculadoraFiniquitoMexicoRoute
  '/calculadoras/calculadora-hipoteca': typeof CalculadorasCalculadoraHipotecaRoute
  '/calculadoras/calculadora-interes-compuesto': typeof CalculadorasCalculadoraInteresCompuestoRoute
  '/calculadoras/calculadora-jubilacion': typeof CalculadorasCalculadoraJubilacionRoute
  '/calculadoras/calculadora-pago-anticipado': typeof CalculadorasCalculadoraPagoAnticipadoRoute
  '/calculadoras/calculadora-pago-deudas': typeof CalculadorasCalculadoraPagoDeudasRoute
  '/calculadoras/calculadora-prestaciones-rd': typeof CalculadorasCalculadoraPrestacionesRdRoute
  '/calculadoras/calculadora-prestamo-empresarial': typeof CalculadorasCalculadoraPrestamoEmpresarialRoute
  '/calculadoras/calculadora-prestamo-estudiantil': typeof CalculadorasCalculadoraPrestamoEstudiantilRoute
  '/calculadoras/calculadora-prestamo-personal': typeof CalculadorasCalculadoraPrestamoPersonalRoute
  '/calculadoras/calculadora-prestamo-vehicular': typeof CalculadorasCalculadoraPrestamoVehicularRoute
  '/calculadoras/calculadora-presupuesto-mensual': typeof CalculadorasCalculadoraPresupuestoMensualRoute
  '/calculadoras/calculadora-refinanciamiento': typeof CalculadorasCalculadoraRefinanciamientoRoute
  '/calculadoras/calculadora-salario-neto': typeof CalculadorasCalculadoraSalarioNetoRoute
  '/calculadoras/calculadora-tarjeta-credito': typeof CalculadorasCalculadoraTarjetaCreditoRoute
  '/calculadoras/comparador-de-prestamos': typeof CalculadorasComparadorDePrestamosRoute
  '/calculadoras/conversor-de-moneda': typeof CalculadorasConversorDeMonedaRoute
  '/blog/': typeof BlogIndexRoute
  '/calculadoras/': typeof CalculadorasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/cookies'
    | '/privacidad'
    | '/sobre-nosotros'
    | '/terminos'
    | '/blog/$slug'
    | '/calculadoras/calculadora-ahorro-meta'
    | '/calculadoras/calculadora-capacidad-endeudamiento'
    | '/calculadoras/calculadora-finiquito-mexico'
    | '/calculadoras/calculadora-hipoteca'
    | '/calculadoras/calculadora-interes-compuesto'
    | '/calculadoras/calculadora-jubilacion'
    | '/calculadoras/calculadora-pago-anticipado'
    | '/calculadoras/calculadora-pago-deudas'
    | '/calculadoras/calculadora-prestaciones-rd'
    | '/calculadoras/calculadora-prestamo-empresarial'
    | '/calculadoras/calculadora-prestamo-estudiantil'
    | '/calculadoras/calculadora-prestamo-personal'
    | '/calculadoras/calculadora-prestamo-vehicular'
    | '/calculadoras/calculadora-presupuesto-mensual'
    | '/calculadoras/calculadora-refinanciamiento'
    | '/calculadoras/calculadora-salario-neto'
    | '/calculadoras/calculadora-tarjeta-credito'
    | '/calculadoras/comparador-de-prestamos'
    | '/calculadoras/conversor-de-moneda'
    | '/blog/'
    | '/calculadoras/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/cookies'
    | '/privacidad'
    | '/sobre-nosotros'
    | '/terminos'
    | '/blog/$slug'
    | '/calculadoras/calculadora-ahorro-meta'
    | '/calculadoras/calculadora-capacidad-endeudamiento'
    | '/calculadoras/calculadora-finiquito-mexico'
    | '/calculadoras/calculadora-hipoteca'
    | '/calculadoras/calculadora-interes-compuesto'
    | '/calculadoras/calculadora-jubilacion'
    | '/calculadoras/calculadora-pago-anticipado'
    | '/calculadoras/calculadora-pago-deudas'
    | '/calculadoras/calculadora-prestaciones-rd'
    | '/calculadoras/calculadora-prestamo-empresarial'
    | '/calculadoras/calculadora-prestamo-estudiantil'
    | '/calculadoras/calculadora-prestamo-personal'
    | '/calculadoras/calculadora-prestamo-vehicular'
    | '/calculadoras/calculadora-presupuesto-mensual'
    | '/calculadoras/calculadora-refinanciamiento'
    | '/calculadoras/calculadora-salario-neto'
    | '/calculadoras/calculadora-tarjeta-credito'
    | '/calculadoras/comparador-de-prestamos'
    | '/calculadoras/conversor-de-moneda'
    | '/blog'
    | '/calculadoras'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/cookies'
    | '/privacidad'
    | '/sobre-nosotros'
    | '/terminos'
    | '/blog/$slug'
    | '/calculadoras/calculadora-ahorro-meta'
    | '/calculadoras/calculadora-capacidad-endeudamiento'
    | '/calculadoras/calculadora-finiquito-mexico'
    | '/calculadoras/calculadora-hipoteca'
    | '/calculadoras/calculadora-interes-compuesto'
    | '/calculadoras/calculadora-jubilacion'
    | '/calculadoras/calculadora-pago-anticipado'
    | '/calculadoras/calculadora-pago-deudas'
    | '/calculadoras/calculadora-prestaciones-rd'
    | '/calculadoras/calculadora-prestamo-empresarial'
    | '/calculadoras/calculadora-prestamo-estudiantil'
    | '/calculadoras/calculadora-prestamo-personal'
    | '/calculadoras/calculadora-prestamo-vehicular'
    | '/calculadoras/calculadora-presupuesto-mensual'
    | '/calculadoras/calculadora-refinanciamiento'
    | '/calculadoras/calculadora-salario-neto'
    | '/calculadoras/calculadora-tarjeta-credito'
    | '/calculadoras/comparador-de-prestamos'
    | '/calculadoras/conversor-de-moneda'
    | '/blog/'
    | '/calculadoras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ContactoRoute: typeof ContactoRoute
  CookiesRoute: typeof CookiesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  TerminosRoute: typeof TerminosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CalculadorasCalculadoraAhorroMetaRoute: typeof CalculadorasCalculadoraAhorroMetaRoute
  CalculadorasCalculadoraCapacidadEndeudamientoRoute: typeof CalculadorasCalculadoraCapacidadEndeudamientoRoute
  CalculadorasCalculadoraFiniquitoMexicoRoute: typeof CalculadorasCalculadoraFiniquitoMexicoRoute
  CalculadorasCalculadoraHipotecaRoute: typeof CalculadorasCalculadoraHipotecaRoute
  CalculadorasCalculadoraInteresCompuestoRoute: typeof CalculadorasCalculadoraInteresCompuestoRoute
  CalculadorasCalculadoraJubilacionRoute: typeof CalculadorasCalculadoraJubilacionRoute
  CalculadorasCalculadoraPagoAnticipadoRoute: typeof CalculadorasCalculadoraPagoAnticipadoRoute
  CalculadorasCalculadoraPagoDeudasRoute: typeof CalculadorasCalculadoraPagoDeudasRoute
  CalculadorasCalculadoraPrestacionesRdRoute: typeof CalculadorasCalculadoraPrestacionesRdRoute
  CalculadorasCalculadoraPrestamoEmpresarialRoute: typeof CalculadorasCalculadoraPrestamoEmpresarialRoute
  CalculadorasCalculadoraPrestamoEstudiantilRoute: typeof CalculadorasCalculadoraPrestamoEstudiantilRoute
  CalculadorasCalculadoraPrestamoPersonalRoute: typeof CalculadorasCalculadoraPrestamoPersonalRoute
  CalculadorasCalculadoraPrestamoVehicularRoute: typeof CalculadorasCalculadoraPrestamoVehicularRoute
  CalculadorasCalculadoraPresupuestoMensualRoute: typeof CalculadorasCalculadoraPresupuestoMensualRoute
  CalculadorasCalculadoraRefinanciamientoRoute: typeof CalculadorasCalculadoraRefinanciamientoRoute
  CalculadorasCalculadoraSalarioNetoRoute: typeof CalculadorasCalculadoraSalarioNetoRoute
  CalculadorasCalculadoraTarjetaCreditoRoute: typeof CalculadorasCalculadoraTarjetaCreditoRoute
  CalculadorasComparadorDePrestamosRoute: typeof CalculadorasComparadorDePrestamosRoute
  CalculadorasConversorDeMonedaRoute: typeof CalculadorasConversorDeMonedaRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CalculadorasIndexRoute: typeof CalculadorasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/': {
      id: '/calculadoras/'
      path: '/calculadoras'
      fullPath: '/calculadoras/'
      preLoaderRoute: typeof CalculadorasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-ahorro-meta': {
      id: '/calculadoras/calculadora-ahorro-meta'
      path: '/calculadoras/calculadora-ahorro-meta'
      fullPath: '/calculadoras/calculadora-ahorro-meta'
      preLoaderRoute: typeof CalculadorasCalculadoraAhorroMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-capacidad-endeudamiento': {
      id: '/calculadoras/calculadora-capacidad-endeudamiento'
      path: '/calculadoras/calculadora-capacidad-endeudamiento'
      fullPath: '/calculadoras/calculadora-capacidad-endeudamiento'
      preLoaderRoute: typeof CalculadorasCalculadoraCapacidadEndeudamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-finiquito-mexico': {
      id: '/calculadoras/calculadora-finiquito-mexico'
      path: '/calculadoras/calculadora-finiquito-mexico'
      fullPath: '/calculadoras/calculadora-finiquito-mexico'
      preLoaderRoute: typeof CalculadorasCalculadoraFiniquitoMexicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-hipoteca': {
      id: '/calculadoras/calculadora-hipoteca'
      path: '/calculadoras/calculadora-hipoteca'
      fullPath: '/calculadoras/calculadora-hipoteca'
      preLoaderRoute: typeof CalculadorasCalculadoraHipotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-interes-compuesto': {
      id: '/calculadoras/calculadora-interes-compuesto'
      path: '/calculadoras/calculadora-interes-compuesto'
      fullPath: '/calculadoras/calculadora-interes-compuesto'
      preLoaderRoute: typeof CalculadorasCalculadoraInteresCompuestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-jubilacion': {
      id: '/calculadoras/calculadora-jubilacion'
      path: '/calculadoras/calculadora-jubilacion'
      fullPath: '/calculadoras/calculadora-jubilacion'
      preLoaderRoute: typeof CalculadorasCalculadoraJubilacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-pago-anticipado': {
      id: '/calculadoras/calculadora-pago-anticipado'
      path: '/calculadoras/calculadora-pago-anticipado'
      fullPath: '/calculadoras/calculadora-pago-anticipado'
      preLoaderRoute: typeof CalculadorasCalculadoraPagoAnticipadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-pago-deudas': {
      id: '/calculadoras/calculadora-pago-deudas'
      path: '/calculadoras/calculadora-pago-deudas'
      fullPath: '/calculadoras/calculadora-pago-deudas'
      preLoaderRoute: typeof CalculadorasCalculadoraPagoDeudasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-prestaciones-rd': {
      id: '/calculadoras/calculadora-prestaciones-rd'
      path: '/calculadoras/calculadora-prestaciones-rd'
      fullPath: '/calculadoras/calculadora-prestaciones-rd'
      preLoaderRoute: typeof CalculadorasCalculadoraPrestacionesRdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-prestamo-empresarial': {
      id: '/calculadoras/calculadora-prestamo-empresarial'
      path: '/calculadoras/calculadora-prestamo-empresarial'
      fullPath: '/calculadoras/calculadora-prestamo-empresarial'
      preLoaderRoute: typeof CalculadorasCalculadoraPrestamoEmpresarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-prestamo-estudiantil': {
      id: '/calculadoras/calculadora-prestamo-estudiantil'
      path: '/calculadoras/calculadora-prestamo-estudiantil'
      fullPath: '/calculadoras/calculadora-prestamo-estudiantil'
      preLoaderRoute: typeof CalculadorasCalculadoraPrestamoEstudiantilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-prestamo-personal': {
      id: '/calculadoras/calculadora-prestamo-personal'
      path: '/calculadoras/calculadora-prestamo-personal'
      fullPath: '/calculadoras/calculadora-prestamo-personal'
      preLoaderRoute: typeof CalculadorasCalculadoraPrestamoPersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-prestamo-vehicular': {
      id: '/calculadoras/calculadora-prestamo-vehicular'
      path: '/calculadoras/calculadora-prestamo-vehicular'
      fullPath: '/calculadoras/calculadora-prestamo-vehicular'
      preLoaderRoute: typeof CalculadorasCalculadoraPrestamoVehicularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-presupuesto-mensual': {
      id: '/calculadoras/calculadora-presupuesto-mensual'
      path: '/calculadoras/calculadora-presupuesto-mensual'
      fullPath: '/calculadoras/calculadora-presupuesto-mensual'
      preLoaderRoute: typeof CalculadorasCalculadoraPresupuestoMensualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-refinanciamiento': {
      id: '/calculadoras/calculadora-refinanciamiento'
      path: '/calculadoras/calculadora-refinanciamiento'
      fullPath: '/calculadoras/calculadora-refinanciamiento'
      preLoaderRoute: typeof CalculadorasCalculadoraRefinanciamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-salario-neto': {
      id: '/calculadoras/calculadora-salario-neto'
      path: '/calculadoras/calculadora-salario-neto'
      fullPath: '/calculadoras/calculadora-salario-neto'
      preLoaderRoute: typeof CalculadorasCalculadoraSalarioNetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/calculadora-tarjeta-credito': {
      id: '/calculadoras/calculadora-tarjeta-credito'
      path: '/calculadoras/calculadora-tarjeta-credito'
      fullPath: '/calculadoras/calculadora-tarjeta-credito'
      preLoaderRoute: typeof CalculadorasCalculadoraTarjetaCreditoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/comparador-de-prestamos': {
      id: '/calculadoras/comparador-de-prestamos'
      path: '/calculadoras/comparador-de-prestamos'
      fullPath: '/calculadoras/comparador-de-prestamos'
      preLoaderRoute: typeof CalculadorasComparadorDePrestamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/conversor-de-moneda': {
      id: '/calculadoras/conversor-de-moneda'
      path: '/calculadoras/conversor-de-moneda'
      fullPath: '/calculadoras/conversor-de-moneda'
      preLoaderRoute: typeof CalculadorasConversorDeMonedaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ContactoRoute: ContactoRoute,
  CookiesRoute: CookiesRoute,
  PrivacidadRoute: PrivacidadRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  TerminosRoute: TerminosRoute,
  BlogSlugRoute: BlogSlugRoute,
  CalculadorasCalculadoraAhorroMetaRoute:
    CalculadorasCalculadoraAhorroMetaRoute,
  CalculadorasCalculadoraCapacidadEndeudamientoRoute:
    CalculadorasCalculadoraCapacidadEndeudamientoRoute,
  CalculadorasCalculadoraFiniquitoMexicoRoute:
    CalculadorasCalculadoraFiniquitoMexicoRoute,
  CalculadorasCalculadoraHipotecaRoute: CalculadorasCalculadoraHipotecaRoute,
  CalculadorasCalculadoraInteresCompuestoRoute:
    CalculadorasCalculadoraInteresCompuestoRoute,
  CalculadorasCalculadoraJubilacionRoute:
    CalculadorasCalculadoraJubilacionRoute,
  CalculadorasCalculadoraPagoAnticipadoRoute:
    CalculadorasCalculadoraPagoAnticipadoRoute,
  CalculadorasCalculadoraPagoDeudasRoute:
    CalculadorasCalculadoraPagoDeudasRoute,
  CalculadorasCalculadoraPrestacionesRdRoute:
    CalculadorasCalculadoraPrestacionesRdRoute,
  CalculadorasCalculadoraPrestamoEmpresarialRoute:
    CalculadorasCalculadoraPrestamoEmpresarialRoute,
  CalculadorasCalculadoraPrestamoEstudiantilRoute:
    CalculadorasCalculadoraPrestamoEstudiantilRoute,
  CalculadorasCalculadoraPrestamoPersonalRoute:
    CalculadorasCalculadoraPrestamoPersonalRoute,
  CalculadorasCalculadoraPrestamoVehicularRoute:
    CalculadorasCalculadoraPrestamoVehicularRoute,
  CalculadorasCalculadoraPresupuestoMensualRoute:
    CalculadorasCalculadoraPresupuestoMensualRoute,
  CalculadorasCalculadoraRefinanciamientoRoute:
    CalculadorasCalculadoraRefinanciamientoRoute,
  CalculadorasCalculadoraSalarioNetoRoute:
    CalculadorasCalculadoraSalarioNetoRoute,
  CalculadorasCalculadoraTarjetaCreditoRoute:
    CalculadorasCalculadoraTarjetaCreditoRoute,
  CalculadorasComparadorDePrestamosRoute:
    CalculadorasComparadorDePrestamosRoute,
  CalculadorasConversorDeMonedaRoute: CalculadorasConversorDeMonedaRoute,
  BlogIndexRoute: BlogIndexRoute,
  CalculadorasIndexRoute: CalculadorasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
